// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDatabase(arg1) {
  return window['go']['main']['App']['ConnectDatabase'](arg1);
}

export function DeleteConfiguration(arg1) {
  return window['go']['main']['App']['DeleteConfiguration'](arg1);
}

export function DisconnectDatabase(arg1) {
  return window['go']['main']['App']['DisconnectDatabase'](arg1);
}

export function ExecuteQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2);
}

export function GetDatabases(arg1) {
  return window['go']['main']['App']['GetDatabases'](arg1);
}

export function GetTableData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3);
}

export function GetTableStats(arg1, arg2) {
  return window['go']['main']['App']['GetTableStats'](arg1, arg2);
}

export function GetTableStructure(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableStructure'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function LoadConfigurations() {
  return window['go']['main']['App']['LoadConfigurations']();
}

export function SaveConfiguration(arg1) {
  return window['go']['main']['App']['SaveConfiguration'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UseDatabase(arg1, arg2) {
  return window['go']['main']['App']['UseDatabase'](arg1, arg2);
}
