// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {model} from '../models';

export function ConnectDatabase(arg1:config.DBConfig):Promise<void>;

export function DeleteConfiguration(arg1:string):Promise<void>;

export function DisconnectDatabase(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<void>;

export function GetDatabases(arg1:string):Promise<Array<string>>;

export function GetTableData(arg1:string,arg2:string,arg3:model.TableDataParams):Promise<model.TableData>;

export function GetTableStats(arg1:string,arg2:string):Promise<model.DatabaseStats>;

export function GetTableStructure(arg1:string,arg2:string,arg3:string):Promise<Array<model.ColumnInfo>>;

export function GetTables(arg1:string,arg2:string):Promise<Array<string>>;

export function LoadConfigurations():Promise<Array<config.DBConfig>>;

export function SaveConfiguration(arg1:config.DBConfig):Promise<void>;

export function TestConnection(arg1:config.DBConfig):Promise<void>;

export function UseDatabase(arg1:string,arg2:string):Promise<void>;
